### ISSUE TITLE
respect system themes

### ISSUE THREAD

**Issue by HookedBehemoth** [fellerts/procal#2]
Opening this up, the bits are bright, not respecting the system theme.
![image](https://user-images.githubusercontent.com/22580720/222916831-ce17a2a2-ee77-4334-8b2e-483e0f2242f0.png)
Having something non-evalable, and toggling "float" fixes the coloring.
![image](https://user-images.githubusercontent.com/22580720/222916938-78a7ffd5-f50a-4b8b-964b-d6462177669b.png)

**Comment by fellerts** [comment]
Thanks for the report. I hacked together some changes in a new branch (fredrik/theme), would you mind taking a look and see if that solves your issue? Note the addition to requirements.txt.

**Comment by fellerts** [comment]
This has been in the master branch for a while, so I'll close this issue.
