### ISSUE TITLE
default font on macOS

### ISSUE THREAD

**Issue by minutello** [fellerts/procal#6]
On macOS, the default font "monospace 10" looks like this:
![before](https://user-images.githubusercontent.com/48494849/222925425-c1df923a-9d71-49d6-ae2f-b32e38814528.png)
This should be changed to "Monaco 12", see:
![after](https://user-images.githubusercontent.com/48494849/222925449-f2982aa1-ffbf-4823-9a3d-3b14ddeea9b6.png)

**Comment by fellerts** [comment]
Thanks, I agree that the default doesn't look very good. I added your suggestions on branch `fredrik/font` (removing the font size override as well), could you please take a look and let me know how it looks?

**Comment by minutello** [comment]
That's perfect now, see:
![ok](https://user-images.githubusercontent.com/48494849/222927189-56a7eafd-dad4-40c4-8b18-7d82cb760785.png)
